---
title: "High throughput thermodynamic calculations"
categories: [software, CALPHAD, "449 Mantei Center"]
---

Pandat 2025 Calculation of Phase Diagrams (CALPHAD) software

::: {.callout-note}
CALPHAD is used to predict phase diagrams and thermodynamic properties of multicomponent systems, enabling the design and optimization of new and existing materials.
:::

## Databases

|----------|------|
| PanAl    | 2024 |
| PanNi    | 2024 |
| PanHEA   | 2025 |
| PanRHEA  | 2024 |
| PanNoble | 2024 |
| PanTi    | 2024 |
| PanIron  | 2024 |

## Modules

* PanPython SDK: Software development kit enabling custom Python interfacing with CALPHAD databases and calculations
* PanPhaseDiagram: Phase diagram calculation and visualization
* PanSolidification: Solidification path calculation and visualization
* PanPhaseField: Phase field simulation of microstructure evolution
* PanOptimizer: Optimization of CALPHAD model parameters
* PanEvolution: Simulation of phase transformations and microstructure evolution




